[project]
name = "svrLSMpy"
version = "0.1.0"
description = "SVR-based Lesion-Symptom Mapping Toolkit with visualization and automated reporting"
authors = [
  { name = "Rohan Jepegnanam", email = "rohantjepegnanam@email.com" }
]
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
  "nilearn",
  "nibabel",
  "pandas",
  "numpy",
  "scikit-learn",
  "statsmodels",
  "matplotlib",
  "scipy",
  "tqdm",
  "atlasreader"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["svrLSMpy"] 

[tool.setuptools.package-data]
"svrLSMpy.resources" = ["*"]
